CREATE TYPE ACCOUNT_TYPE AS ENUM ('CHECKING', 'SAVING', 'PRIVATE_LOAN');

CREATE DOMAIN IBAN AS VARCHAR(22) CHECK ( VALUE ~* '^[a-zA-Z0-9]{22}$' );


CREATE TABLE account (
	iban IBAN PRIMARY KEY,
	create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	type ACCOUNT_TYPE NOT NULL,
	LOCKED BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE TRANSACTION (
	id BIGSERIAL PRIMARY KEY,
	create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	sender_iban IBAN REFERENCES account (iban) ON DELETE RESTRICT,
	receiver_iban IBAN NOT NULL REFERENCES account (iban) ON DELETE RESTRICT,
	amount BIGINT NOT NULL
);